name: Verify
run-name: "Verify ${{ github.event.pull_request && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) || github.ref }}"

on:
  pull_request:
    branches: [main]
  push:
  workflow_call:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm
      - run: pnpm i
      - run: pnpm build
      - run: pnpm test
      - run: pnpm fmtcheck
      - run: echo 'Papilio palinurus'
